# Generated by Django 4.2.4 on 2023-11-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('japanese_name', models.CharField(max_length=255)),
                ('english_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'character',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_url', models.CharField(max_length=1000)),
                ('date_time', models.CharField(max_length=225)),
            ],
            options={
                'db_table': 'log',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.CharField(max_length=255)),
                ('item_code', models.CharField(max_length=255, null=True)),
                ('image_url', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('listing_date', models.CharField(max_length=255, null=True)),
                ('countdowned_date', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_rate', models.CharField(max_length=255)),
                ('profit_rate', models.CharField(max_length=255)),
                ('countdown_duration', models.CharField(max_length=255)),
                ('countdown_money', models.CharField(max_length=255)),
                ('endlist_duration', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=10000)),
            ],
            options={
                'db_table': 'setting',
            },
        ),
    ]
